# Generated by Django 3.2.14 on 2024-10-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsvenue',
            name='societies',
            field=models.ManyToManyField(blank=True, to='registration.Society'),
        ),
    ]
