# Generated by Django 3.2.14 on 2024-10-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_sportsvenue_societies'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='societies', to='registration.Coaching'),
        ),
        migrations.AlterField(
            model_name='sportsvenue',
            name='societies',
            field=models.ManyToManyField(blank=True, related_name='venues', to='registration.Society'),
        ),
    ]
