# Generated by Django 3.2.14 on 2024-10-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20241008_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile_number',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
