# Generated by Django 3.2.14 on 2024-10-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_contact_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_gateway',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='registration',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
